# Generated by Django 5.2.13 on 2026-05-06 19:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContatoONG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_contato', models.EmailField(max_length=254, verbose_name='E-mail de contato')),
                ('telefone_contato', models.CharField(help_text='Somente números, com DDI e DDD. Ex: 5511999999999', max_length=20, validators=[django.core.validators.RegexValidator(message='Informe apenas dígitos, incluindo DDI e DDD (10 a 15 números).', regex='^\\d{10,15}$')], verbose_name='Telefone de contato')),
                ('whatsapp_contato', models.CharField(help_text='Somente números, com DDI e DDD. Ex: 5511999999999', max_length=20, validators=[django.core.validators.RegexValidator(message='Informe apenas dígitos, incluindo DDI e DDD (10 a 15 números).', regex='^\\d{10,15}$')], verbose_name='WhatsApp de contato')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contato da ONG',
                'verbose_name_plural': 'Contatos da ONG',
                'ordering': ['-atualizado_em'],
            },
        ),
    ]
