# Generated by Django 5.2.13 on 2026-05-06 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contato', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContatoONG',
        ),
    ]
