# Generated by Django 5.2.13 on 2026-05-20 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contato', '0002_delete_contatoong'),
        ('contato', '0002_seed_default'),
    ]

    operations = [
    ]
